#docker-compose file
version: '3.3'

services:
  dev:
    container_name: nestjs_chess_dev
    image: nestjs_chess_dev:1.0.0
    build:
      context: .
      dockerfile: ./Dockerfile
    command: npm run start:dev
    ports:
      - ${APP_PORT}:${APP_PORT}
    networks:
      - nesjs-network
    depends_on:
      - mongodb
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
  mongodb:
    image: mongo:latest
    container_name: container_mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGODB_DB_NAME}
    volumes:
      - ./mongo-init/:/docker-entrypoint-initdb.d/:ro
    ports:
      - ${MONGODB_PORT}:${MONGODB_PORT}
    networks:
      - nesjs-network
    restart: always
  prod:
    container_name: nestjs_chess_prod
    image: nestjs_chess_prod:1.0.0
    build:
      context: .
      dockerfile: ./Dockerfile
    command: npm run start:prod
    ports:
      - ${APP_PORT}:${APP_PORT}
    networks:
      - nesjs-network
    depends_on:
      - mongodb
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
networks:
  nesjs-network:
    driver: bridge
